apiVersion: batch/v1
kind: Job
metadata:
  name: covid-producer-streaming
spec:
  template:
    metadata:
      labels:
        app: covid-producer-streaming
    spec:
      containers:
        - name: producer
          image: python:3.9-slim
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install --no-cache-dir kafka-python && \
              # Wait for data file
              while [ ! -f /app/data/covid_0.csv ]; do sleep 2; done
              echo "Data found. Starting streaming..."
              # Chạy script một lần rồi kết thúc
              python -u /app/code/kafka_producer_streaming.py
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: TOPIC_NAME
              value: "covid-raw"
            - name: DATA_FILE
              value: "/app/data/covid_0.csv"
            - name: DAY_DELAY
              value: "0.5"
          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: code-volume
              mountPath: /app/code
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: code-volume
          configMap:
            name: producer-streaming-script
        - name: data-volume
          emptyDir: {}
      restartPolicy: OnFailure
  backoffLimit: 1
