# Internal Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: ClusterIP
  selector:
    app: spark-master
  ports:
  - name: cluster
    port: 7077
    targetPort: 7077
  - name: web-ui
    port: 8080
    targetPort: 8080
---
# NodePort Service Spark Master
apiVersion: v1
kind: Service
metadata:
  name: spark-master-external
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
  - name: web-ui
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: cluster
    port: 7077
    targetPort: 7077
    nodePort: 30077
---
# Deployment Spark Master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: apache/spark:4.1.0-python3
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        env:
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: SPARK_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPARK_DRIVER_BIND_ADDRESS
          value: "0.0.0.0"
        - name: SPARK_CONF_DIR
          value: "/opt/spark/conf"
        resources:
          limits:
            memory: "1Gi"
---
# Deployment Spark Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: apache/spark:4.1.0-python3
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        env:
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: "1G"
        resources:
          limits:
            memory: "2Gi"
